apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      db: auth-mongo

  template:
    metadata:
      labels:
        db: auth-mongo

    spec:
      containers:
        - name: auth-mongo
          image: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-serv

spec:
  selector:
    db: auth-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
