apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-mongo-depl

spec:
  replicas: 1

  selector:
    matchLabels:
      db: coupon-mongo

  template:
    metadata:
      labels:
        db: coupon-mongo
    spec:
      containers:
        - name: coupon-mongo
          image: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: coupon-mongo-serv

spec:
  selector:
    db: coupon-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
