name: test-auth-serv

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu@latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v3

      - name: test
      - run: cd auth && npm install && npm run test
